services:
  backend-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    restart: on-failure
    networks:
      - mongo_network
    ports:
      - 3000:3000
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo_container
    restart: on-failure
    networks:
      - mongo_network
    ports:
      - 27017:27017
    env_file:
      - .env.production
    volumes:
      - mongo-data:/data/db

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
